# Generated by Django 5.2.6 on 2025-09-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('logo_url', models.URLField()),
                ('pais_origen', models.CharField(max_length=100)),
            ],
        ),
    ]
