# Generated by Django 5.2.6 on 2025-09-11 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes_servicios', '0002_cliente_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='correo',
        ),
    ]
